name: No Duplications

on: [push, pull_request]

jobs:
  nodups:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install jscpd
      run: sudo npm install -g jscpd

    - name: No Duplication beyond 3 lines
      run: jscpd . --min-lines 13 --min-tokens 148 --threshold 0
